version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx-gateway
    ports:
      - "8080:80"   # Host:Container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html:ro
    networks:
      - app-net

networks:
  app-net:
    driver: bridge